version: "3.3"

services: 
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 1000:3000
  
  my_database:
    image: mongo.latest
    ports: 
      - 1001:27017