version: "3.3"

services:
  my_backend:
    build:
      context: .
      dockerfile: dockerfile.express
    ports:
      - 3000:3000
  
  my_database:
    build:
      context: .
      dockerfile: dockerfile.mongodb
    ports:
      - 27017:27017