version: "3.3"

service:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1000:3000
  
  my_database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 1001:27017